name: Serializer
run-name: Serializer Testing 🚀
on: [push]
jobs:
    build:
        
        runs-on: ${{ matrix.os}}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version:  ["3.7", "3.8", "3.9", "3.10", "3.11"]
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}
            - name: Test with unittest
              run: |
                python testStringListSerializer.py